/**
 * Antigravity managed-agent integration ("Agent Mode", opt-in).
 *
 * When Agent Mode is on, quizzes are GENERATED by the Gemini managed agent
 * (`antigravity-preview-05-2026`) via the Interactions API — using the SAME
 * system prompts as the normal pipeline, grounded ONLY in the lecture material
 * (`tools: []` → no web search). The agent's autonomous reasoning loop produces
 * a higher-quality quiz than a single model call.
 *
 * We call the REST endpoint directly (no @google/genai version dependency).
 *
 * SAFETY CONTRACT: this function never throws. It returns the generated quiz on
 * success, or **null** on ANY problem (missing key, non-2xx, timeout,
 * unparseable response, or output that isn't a real quiz). The caller then falls
 * back to the normal gemini-3.5-flash generation — so Agent Mode can never break
 * or empty a quiz. Every fallback is surfaced via `onProgress` so it's visible
 * in the UI (not silent), and logged under `[agent]`.
 */

const AGENT_MODEL = "antigravity-preview-05-2026";
const INTERACTIONS_URL = "https://generativelanguage.googleapis.com/v1beta/interactions";
const API_REVISION = "2026-05-20";
/** Bounded so the rest of the pipeline still fits inside the route's maxDuration. */
const AGENT_TIMEOUT_MS = 240_000;
/** Keep the payload sane; the agent compacts context internally anyway. */
const MAX_MATERIAL_CHARS = 120_000;

/** Does the text satisfy our quiz contract (section markers or Aufgabe N)? */
function looksLikeQuiz(text: string): boolean {
  return /={3,}\s*STUDENT_QUIZ_START/i.test(text) || /Aufgabe\s+\d+/i.test(text);
}

/** Best-effort extraction of the agent's final text from the REST response. */
function extractOutputText(data: unknown): string {
  if (!data || typeof data !== "object") return "";
  const d = data as Record<string, unknown>;
  if (typeof d.output_text === "string") return d.output_text;
  if (typeof d.outputText === "string") return d.outputText as string;
  const out = d.output ?? d.outputs;
  if (Array.isArray(out)) {
    const parts: string[] = [];
    for (const item of out) {
      if (typeof item === "string") parts.push(item);
      else if (item && typeof item === "object") {
        const rec = item as Record<string, unknown>;
        const t = rec.text ?? rec.content ?? rec.output_text;
        if (typeof t === "string") parts.push(t);
      }
    }
    if (parts.length) return parts.join("\n");
  }
  return "";
}

/**
 * Generate a quiz with the managed agent, using the given system instruction
 * (the SAME prompt the normal pipeline uses) and the lecture material as text.
 * Returns the generated quiz, or `null` on any failure (caller falls back to
 * the normal gemini-3.5-flash generation).
 */
export async function generateQuizWithAgent(params: {
  instruction: string;
  material: string;
  label?: string;
  onProgress?: (msg: string) => void;
}): Promise<string | null> {
  const { instruction, material, label = "Quiz", onProgress } = params;
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    onProgress?.("Agent: kein GEMINI_API_KEY — Standard-Generierung wird genutzt.");
    return null;
  }

  const input = [
    instruction,
    "",
    "=== VORLESUNGSMATERIAL / KONTEXT (stütze dich AUSSCHLIESSLICH hierauf, erfinde nichts) ===",
    (material || "").slice(0, MAX_MATERIAL_CHARS) || "(kein Text)",
    "",
    "Erzeuge JETZT die finale Ausgabe — exakt im geforderten Markdown-Format mit allen ===MARKER=== Blöcken (z. B. ===STUDENT_QUIZ_START===, ===COVERAGE_LEDGER_START===). KEIN JSON, keine Vorrede, keine Code-Blöcke.",
  ].join("\n");

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), AGENT_TIMEOUT_MS);
  try {
    onProgress?.(`Agent generiert ${label} (nur dein Material)…`);
    const res = await fetch(INTERACTIONS_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": apiKey,
        "Api-Revision": API_REVISION,
      },
      // tools: [] → grounded reasoning only (no web search, URL fetch, or code).
      body: JSON.stringify({ agent: AGENT_MODEL, input, environment: "remote", tools: [] }),
      signal: controller.signal,
    });

    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      console.error(`[agent] Interactions API ${res.status} — fallback to normal generation. ${detail.slice(0, 400)}`);
      onProgress?.(`Agent nicht erreichbar (HTTP ${res.status}) — Standard-Generierung.`);
      return null;
    }

    const data = await res.json().catch(() => null);
    const out = extractOutputText(data).trim();
    if (out && looksLikeQuiz(out)) {
      console.log(`[agent] ${label}: generated ${out.length} chars via managed agent.`);
      return out;
    }
    console.warn(`[agent] ${label}: empty or non-quiz agent output — fallback. Head: ${out.slice(0, 200)}`);
    onProgress?.("Agent-Ausgabe ungültig — Standard-Generierung.");
    return null;
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(`[agent] ${label}: call failed — fallback. ${msg}`);
    onProgress?.("Agent-Fehler — Standard-Generierung.");
    return null;
  } finally {
    clearTimeout(timer);
  }
}
