-- Agent Mode reverted: this migration is intentionally a no-op.
-- (The agentMode column was removed from schema.prisma. If your live DB still
--  has a leftover "agentMode" column from earlier testing, it is harmless and
--  simply ignored by Prisma.)
